services:
  psql-db:
    image: postgres:17.6
    container_name: word_forge
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wordforge_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
